\RequirePackage[utf8]{inputenc}
\RequirePackage[T1]{fontenc}
\RequirePackage[french]{babel}
\RequirePackage{apalike}
\RequirePackage[default, oldstyle, scale=.95]{opensans} % police Open Sans
\RequirePackage{amsmath}
\RequirePackage{amsfonts}
\RequirePackage{amssymb}
\RequirePackage{caption}
\captionsetup[figure]{font=small,labelfont=small}
\RequirePackage{xcolor} % où color selon l'installation
\RequirePackage[xindy, acronyms]{glossaries}
\RequirePackage{mdframed}
\RequirePackage{multirow} %% Pour mettre un texte sur plusieurs rangées
\RequirePackage{multicol} %% Pour mettre un texte sur plusieurs colonnes
\RequirePackage{tikz}
\RequirePackage{graphicx}
\RequirePackage[absolute]{textpos} 
\RequirePackage{colortbl}
\RequirePackage{array}
\RequirePackage[a4paper]{geometry}
\RequirePackage{subfloat}
\RequirePackage{subcaption}
\RequirePackage{titlesec}
\RequirePackage{hyperref}
\hypersetup{ % paramétrage couleur des liens hypertextes, toujours garder colorlinks=true
    colorlinks=true,
    linkcolor=black,
    urlcolor=A5}

\graphicspath{{./images/}} %Chemin vers les images
